### ISSUE TITLE
can you give me example for multi accout,..?

### ISSUE THREAD

**Issue by Voldigodsx** [maldiharyojudanto/yescoin-bot#1]

**Comment by maldiharyojudanto** [comment]
> _No description provided._

Sure, like this sir

<img width="217" alt="image" src="https://github.com/maldiharyojudanto/yescoin-bot/assets/76139419/6346ba7e-c145-43d6-9525-aff63363dc56">

**Comment by maldiharyojudanto** [comment]
> > > _No description provided._
> > 
> > 
> > Sure, like this sir
> > <img alt="image" width="217" src="https://private-user-images.githubusercontent.com/76139419/339061697-6346ba7e-c145-43d6-9525-aff63363dc56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNDE3NzYsIm5iZiI6MTcxODI0MTQ3NiwicGF0aCI6Ii83NjEzOTQxOS8zMzkwNjE2OTctNjM0NmJhN2UtYzE0NS00M2Q2LTk1MjUtYWZmNjMzNjNkYzU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDAxMTc1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhMTZhZWViOGUzMzJhN2NhMDZmNGFmNzNhNzhhZjA5NzZkYzk3YThhMzYwZDgwYmY4ZDc1NWI0NWU0ZjU3MTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DeRavdIZ3xW7sioEZ_iayWwyiYgsq1_BGjI7MtXp7mM">
> 
> ![image](https://private-user-images.githubusercontent.com/108380151/339175289-f443abfa-4c1e-40b1-bbef-233c20377605.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNDY5NTgsIm5iZiI6MTcxODI0NjY1OCwicGF0aCI6Ii8xMDgzODAxNTEvMzM5MTc1Mjg5LWY0NDNhYmZhLTRjMWUtNDBiMS1iYmVmLTIzM2MyMDM3NzYwNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxM1QwMjQ0MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYmEyNGM4ZDNiNWNjYjI2M2E3M2ZmZjhkNjkzYTg0MzdiNzVjZDMwMWE4OTQ4MmI1MDY4NDAyNWM5YjI4MWQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kxolJZvhE9Iy-68Uw4i36Dejmb3baoQ_PGpYSMI1sXY) i got this error when try running it

I am sorry, just updated the main.py now. clone/download back and get the query/init data from Application - Storage session - Select '__telegram__initParams' - Copy the value of tgWebAppData 

Example : ```user=%7B%22id%22%xxxxxxxxxx````

<img width="589" alt="image" src="https://github.com/maldiharyojudanto/yescoin-bot/assets/76139419/61566bec-763c-4007-ae4c-6a61cf11b7a4">

Thank you for the feedback

**Comment by toastyy00** [comment]
still facing same error

**Comment by maldiharyojudanto** [comment]
> still facing same error
> 
> ![image](https://private-user-images.githubusercontent.com/108380151/339195611-cc432997-1390-4637-8430-d1fade76fba6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNDgzNTQsIm5iZiI6MTcxODI0ODA1NCwicGF0aCI6Ii8xMDgzODAxNTEvMzM5MTk1NjExLWNjNDMyOTk3LTEzOTAtNDYzNy04NDMwLWQxZmFkZTc2ZmJhNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxM1QwMzA3MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMzQxNjdjZTFlZTM4ZDAwMTlkMWZkZjgxZDUyYjNjODg1M2Y3YTBkOWQwMzczYzE1MzA2OTNhYzlhNWM1OWIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8IhDQUF_sDkrOeJaGvhf7OSzOUujBblxvKpNIT7e5fA)

Try to check the result of token_new first by ```print(token_new)```

**Comment by toastyy00** [comment]
> token_new

![image](https://github.com/maldiharyojudanto/yescoin-bot/assets/108380151/4532ea38-1b73-4054-ba85-663805101d45)

gini bang

**Comment by maldiharyojudanto** [comment]
> > token_new
> 
> ![image](https://private-user-images.githubusercontent.com/108380151/339201758-4532ea38-1b73-4054-ba85-663805101d45.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNTAyMzIsIm5iZiI6MTcxODI0OTkzMiwicGF0aCI6Ii8xMDgzODAxNTEvMzM5MjAxNzU4LTQ1MzJlYTM4LTFiNzMtNDA1NC1iYTg1LTY2MzgwNTEwMWQ0NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxM1QwMzM4NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMWY3Y2Q2OTkyODM3ODk1YzMxNzMwY2VlMDc1OWNjMThiODNmYmU3NTI0N2MzNDFkMGZkMGRlNGJmM2UwZjNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qYsTGx0mhHJSulre2Jf0JDr3XGN0pUdV-BvApH45t3M)
> 
> gini bang

resultnya masih none bg tokennya gak ada, itu karena salah format di input payloadnya pas createToken, harus di parsing dulu query/init data mentahnya jadi kayak gini

<img width="697" alt="image" src="https://github.com/maldiharyojudanto/yescoin-bot/assets/76139419/0e850264-0c9a-46a5-a7b5-73b449dca23e">

itu jadi input masukan payload di createToken
<img width="111" alt="image" src="https://github.com/maldiharyojudanto/yescoin-bot/assets/76139419/813c4d38-1003-4ea8-825e-4c552610f6b7">

**Comment by toastyy00** [comment]
> a salah format di input payloadnya pas createToken, harus di parsing dulu query/init data mentahnya jadi kayak gini

jadi nunggu scriptnya di fix dulu? atau error nya cuma di saya?

**Comment by maldiharyojudanto** [comment]
> > a salah format di input payloadnya pas createToken, harus di parsing dulu query/init data mentahnya jadi kayak gini
> 
> jadi nunggu scriptnya di fix dulu? atau error nya cuma di saya?

udah saya fix, silakan di clone/download ulang main.py atau repository nya

isi querydata.txt nya pakai format seperti contoh dan gambar di bawah ini

Contoh: ```user=%7B%22id%22%xxxxxxxxxx```

<img width="589" alt="image" src="https://github.com/maldiharyojudanto/yescoin-bot/assets/76139419/61566bec-763c-4007-ae4c-6a61cf11b7a4">

Semoga berhasil

**Comment by toastyy00** [comment]
> > > a salah format di input payloadnya pas createToken, harus di parsing dulu query/init data mentahnya jadi kayak gini
> > 
> > 
> > jadi nunggu scriptnya di fix dulu? atau error nya cuma di saya?
> 
> udah saya fix, silakan di clone/download ulang main.py atau repository nya
> 
> isi querydata.txt nya pakai format seperti contoh dan gambar di bawah ini
> 
> Contoh: `user=%7B%22id%22%xxxxxxxxxx`
> 
> <img alt="image" width="589" src="https://private-user-images.githubusercontent.com/76139419/339191946-61566bec-763c-4007-ae4c-6a61cf11b7a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNTI1MTYsIm5iZiI6MTcxODI1MjIxNiwicGF0aCI6Ii83NjEzOTQxOS8zMzkxOTE5NDYtNjE1NjZiZWMtNzYzYy00MDA3LWFlNGMtNmE2MWNmMTFiN2E0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDA0MTY1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0MGEzNWNhOWVkMjRkMDJhMjE3ZjM4YWQxOTc0ODE3ZGU3MTg3MWRhOTM5M2JmYjRhZGVjNmU1YWMzY2ZiMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F1F5Rn1wnvtuHFXvcTMhkbF67emxlGUQHbWDlm5qZgU">
> Semoga berhasil

tadi test pake akun tele lain work, pas coba di tele utama(premium) malah error kyk tadi, query nya juga beda bang 
![image](https://github.com/maldiharyojudanto/yescoin-bot/assets/108380151/a8bb7026-a9a0-41ec-9349-180fc0f27969)

**Comment by toastyy00** [comment]
udh work, ternyata gara2 nama tele saya pake karakter aneh (ａｒｉｆ) jadi parsingnya ga valid
